name: create-runner
on:
  workflow_dispatch
jobs:
  create-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list file
        run: ls -l