name: create-runner

on:
  workflow_dispatch:

jobs:
  create-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list file
        run: ls -l

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check secrets exist
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "Missing AWS key"; exit 1; fi

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v5.1.1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve